### ISSUE TITLE
caffemodel在哪里呢

### ISSUE THREAD

**Issue by hpc203** [ManaliSeth/Athlete-Pose-Detection#1]
程序文件夹里只有prototxt，没有caffemodel，请提供caffemodel

**Comment by ManaliSeth** [comment]
.caffemodel file size exceeds GitHub's file size limit of 100.00 MB
You can find it here: https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe-models/tree/master/caffe_models/openpose/caffe_model
